# Generated by Django 6.0.2 on 2026-05-07 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('payment_id', models.CharField(max_length=100)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Templeapp.loginuser')),
            ],
        ),
        migrations.CreateModel(
            name='DarshanBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('darshan_date', models.DateField()),
                ('slot', models.CharField(choices=[('6AM - 8AM', '6AM - 8AM'), ('8AM - 10AM', '8AM - 10AM'), ('10AM - 12PM', '10AM - 12PM'), ('4PM - 6PM', '4PM - 6PM')], max_length=50)),
                ('booking_id', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Templeapp.loginuser')),
            ],
        ),
        migrations.CreateModel(
            name='SevaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=10)),
                ('seva_name', models.CharField(choices=[('Suprabhata Seva', 'Suprabhata Seva'), ('Archana', 'Archana'), ('Kalyanotsavam', 'Kalyanotsavam'), ('Thomala Seva', 'Thomala Seva')], max_length=200)),
                ('seva_time', models.CharField(choices=[('6AM', '6AM'), ('9AM', '9AM'), ('12PM', '12PM'), ('6PM', '6PM')], max_length=50)),
                ('seva_date', models.DateField()),
                ('booking_id', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Templeapp.loginuser')),
            ],
        ),
    ]
