# Generated by Django 6.0.2 on 2026-05-13 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('amount', models.IntegerField()),
                ('payment_id', models.CharField(max_length=100)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Templeapp.loginuser')),
            ],
        ),
        migrations.CreateModel(
            name='DarshanBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('darshan_date', models.DateField()),
                ('slot', models.CharField(choices=[('6AM - 8AM', '6AM - 8AM'), ('8AM - 10AM', '8AM - 10AM'), ('10AM - 12PM', '10AM - 12PM'), ('4PM - 6PM', '4PM - 6PM')], max_length=50)),
                ('booking_id', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Templeapp.loginuser')),
            ],
        ),
        migrations.CreateModel(
            name='SevaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=10)),
                ('seva_name', models.CharField(choices=[('Suprabhata Seva - 3:00 AM', 'Suprabhata Seva - 3:00 AM'), ('Thomala Seva - 4:00 AM', 'Thomala Seva - 4:00 AM'), ('Archana - 4:30 AM', 'Archana - 4:30 AM'), ('Kalyanotsavam - 10:00 AM', 'Kalyanotsavam - 10:00 AM'), ('Unjal Seva - 7:00 PM', 'Unjal Seva - 7:00 PM'), ('Sahasra Deepalankara Seva - 5:30 PM', 'Sahasra Deepalankara Seva - 5:30 PM')], max_length=200)),
                ('seva_date', models.DateField()),
                ('booking_id', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Templeapp.loginuser')),
            ],
        ),
    ]
